// <auto-generated />
using System;
using API_Financas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Financas.Migrations
{
    [DbContext(typeof(FinancasContext))]
    [Migration("20250801195413_versao1")]
    partial class versao1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("API_Financas.Models.CategoriaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdCategoria")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoria");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("API_Financas.Models.TipoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdTipo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdTipo");

                    b.ToTable("Tipos");
                });

            modelBuilder.Entity("API_Financas.Models.TransacaoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTipo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Transacoes");
                });

            modelBuilder.Entity("API_Financas.Models.CategoriaModel", b =>
                {
                    b.HasOne("API_Financas.Models.TransacaoModel", null)
                        .WithMany("Categorias")
                        .HasForeignKey("IdCategoria");
                });

            modelBuilder.Entity("API_Financas.Models.TipoModel", b =>
                {
                    b.HasOne("API_Financas.Models.TransacaoModel", null)
                        .WithMany("Tipos")
                        .HasForeignKey("IdTipo");
                });

            modelBuilder.Entity("API_Financas.Models.TransacaoModel", b =>
                {
                    b.Navigation("Categorias");

                    b.Navigation("Tipos");
                });
#pragma warning restore 612, 618
        }
    }
}
